import "./chat.css";
import { Check, Copy, Download, Volume2 } from "lucide-react";
import { useState } from "react";

type Props = {
  sender: "user" | "sentinel";
  text: string;
  timestamp: string;
  imageUrl?: string;
  imagePrompt?: string;
};

export default function ChatMessage({
  sender,
  text,
  timestamp,
  imageUrl,
  imagePrompt,
}: Props) {
  const isUser = sender === "user";
  const [copied, setCopied] = useState(false);

  async function copyMessage() {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1400);
  }

  function speakMessage() {
    speechSynthesis.cancel();
    speechSynthesis.speak(new SpeechSynthesisUtterance(text));
  }

  return (
    <div
      className={`message-row ${
        isUser ? "user" : "sentinel"
      }`}
    >
      <article className="message">

        <div className="message-avatar">
          {isUser ? "👤" : "🤖"}
        </div>

        <div className="message-main">

          <div className="message-top">

            <div>

              <h4>
                {isUser ? "You" : "Sentinel"}
              </h4>

              <span>{timestamp}</span>

            </div>

            <div className="message-tools"><button type="button" title="Copy message" onClick={() => void copyMessage()}>{copied ? <Check size={16}/> : <Copy size={16}/>}</button>{!isUser && <button type="button" title="Read aloud" onClick={speakMessage}><Volume2 size={16}/></button>}</div>

          </div>

          <div className="message-text">
            {text}
          </div>

          {imageUrl && <figure className="generated-image-card">
            <img src={imageUrl} alt={imagePrompt || "Image generated by Sentinel"} />
            <figcaption>
              <span>{imagePrompt || "Generated by Sentinel"}</span>
              <a href={imageUrl} download title="Save generated image"><Download size={17}/> Save image</a>
            </figcaption>
          </figure>}

        </div>

      </article>
    </div>
  );
}
